# coding: utf-8

from hmtl.modules.parsers.biaffine_dependency_parser_for_pipeline import BiaffineDependencyParserForPipeline
from hmtl.modules.parsers.biaffine_dependency_parser_custom import BiaffineDependencyParserCustom
